CREATE TABLE IF NOT EXISTS deaths (
    "death_id" INT PRIMARY KEY,
    "death" TEXT,
    "cause" TEXT,
    "responsible" TEXT,
    "last_words" TEXT,
    "season" INT,
    "episode" INT,
    "number_of_deaths" INT,
    FOREIGN KEY(season, episode) REFERENCES episodes(season, episode)
);
INSERT INTO deaths VALUES (40,'Bodyguards of Gus Fring','Multiple gunshots.','Walter White','What, you got a problem with stairs?',4,13,2),
	(28,'Cartel Assassins','Shot in close range.','Mike Ehrmantraut','Unknown',4,4,2),
	(23,'Rival Dealers','Ran over with a van, then shot in the head.','Walter White','Unknown',3,12,2),
	(34,'Juarez Cartel members','Poisoned.','Gustavo Fring','Unknown',4,10,11),
	(20,'Juan Bolsa''s bodyguards','Shot repeatedly.','Mexican federales. (Gustavo Fring associated)','Unknown',3,8,2),
	(56,'Declan''s men and his cook.','Gunshot.','White Supremacist gang (Lydia Rodarte-Quayle)','Unknown',5,10,9),
	(61,'White Supremacist gang members','Shot by remote-activated machine gun.','Walter White','Unknown',5,16,6),
	(13,'Mexican passengers','Shot in close proximity, left in truck that was set on fire.','The Counsins','Unknown',3,1,10),
	(16,'Deputy Bobby Kee','Struck in the back with an axe.','Marco Salamanca (The Counsins)','On your knees or I''ll fire!',3,6,1),
	(17,'Unnamed Man','Shot in the chest and head.','Marco Salamanca (The Counsins)','Jesus.',3,7,1),
	(25,'Gale Boetticher','Shot in the head.','Jesse Pinkman (On orders from Walter White)','You don''t have to do this.',3,13,1),
	(18,'Marco Salamanca','Shot in the head.','Hank Schrader (Henry Schrader, Gustavo Fring associated)','Too easy',3,7,1),
	(30,'Los Pollos guards','Suffocated by exhaust in the back of a truck.','Juarez Cartel','Unknown',4,6,2),
	(24,'Cartel Assassins','Shot repeatedly.','Mike Erhmantraut (Gustavo Fring associated)','Unknown',3,13,4),
	(38,'Tyrus Kitt','Blown up by pipe bomb detonated by a wheel-chair bell.','Hector Salamanca and Walter White','It''s clear',4,13,1),
	(36,'Joaquin Salamanca','Multiple gunshots.','Jesse Pinkman','Unknwon',4,10,1),
	(43,'Chris Mara','Shot repeatedly in the chest.','Mike Ehrmantraut','Listen, Mike',5,1,1),
	(39,'Gustavo Fring','Blown up by pipe bomb detonated by a wheel-chair bell. Also lost the right side of his face.','Hector Salamanca and Walter White','Hall!',4,13,1),
	(41,'Peter Schuler','Suicide using a defibrillator.','Himself','Yes, Ms. Tromel.',5,1,1),
	(42,'Duane Chow','Shot in the head.','Chris Mara (Lydia Rodart-Quayle associated)','Unknown',5,1,1),
	(11,'Jane Margolis','Heroin overdose. Asphyxiated on her own vomit.','Herself and Walter White','Unknown',2,12,1),
	(22,'Tomas Cantillo','Unknown (presumably shot).','Rival Dealers','Unknown',3,12,1),
	(2,'Krazy-8','Strangled with a bike lock.','Walter White','Unlock me, Walter',1,3,1),
	(27,'Los Pollos driver','Shot in close range.','Juarez Cartel','No, no, no!',4,4,1),
	(32,'Nick','Shot by a sniper rifle.','Gaff','Unknown',4,9,1),
	(6,'Convenience Clerk','Stabbed during ATM theft.','Spooge','Unknown',2,6,1),
	(7,'Spooge','Head crushed by ATM.','Spooge''s Lady','Skank!',2,6,1),
	(29,'Los Pollos driver','Multiple gun shots.','Juarez Cartel','No, no, no, no, no!',4,6,1),
	(15,'Mrs. Peyketewa','Unknown cause of death.','The Counsins','Unknown',3,6,1),
	(3,'No-Doze','Beaten to death.','Tuco Salamanca','No Tuco, I''m just.. I''m just saying.',1,7,1),
	(8,'Tortuga','Decapitated.','Marco Salamanca','Thank you, boss.',2,7,1),
	(9,'Unnamed DEA agent','Blown up by bomb in tortoise.','The Cousins','Unknown',2,7,1),
	(33,'Don Eladio','Poisoned.','Gustavo Fring','¿Tú?',4,10,1),
	(35,'Gaff','Garroted (Strangled by wire).','Mike Ehrmantraut','¡Salud!',4,10,1),
	(31,'Max Arciniega','Shot in the head.','Hector Salamanca','I swear to God.',4,8,1),
	(19,'Leonel Salamanca','Unknown poison in the hospital.','Mike Ehrmantraut (Gustavo Fring associated)','Finish him',3,8,1),
	(21,'Juan Bolsa','Shot repeatedly.','Mexican federales. (Gustavo Fring associated)','What the hell is going on?',3,8,1),
	(37,'Hector Salamanca','Blown up by pipe bomb detonated by a wheel-chair bell.','Himself and Walter White','*grunting',4,13,1),
	(44,'Drew Sharp','Shot in the head.','Todd Alquist','Unknown',5,5,1),
	(45,'Mike Ehrmantraut','Shot in the gut.','Walter White','Shut the fuck up and let me die in peace.',5,7,1),
	(46,'Dan Wachsberger','Stabbed.','Prison inmate, on orders from Jack Welker (contracted by Walter White)','*screaming',5,8,1),
	(47,'Ron Forenall','Stabbed.','Prison inmate, on orders from Jack Welker (contracted by Walter White)','Hey!',5,8,1),
	(48,'Jack McGann','Stabbed.','Prison inmate, on orders from Jack Welker (contracted by Walter White)','Unknown',5,8,1),
	(49,'Andrew Holt','Stabbed.','Prison inmate, on orders from Jack Welker (contracted by Walter White)','Unknown',5,8,1),
	(50,'Anthony Perez','Stabbed.','Prison inmate, on orders from Jack Welker (contracted by Walter White)','Unknown',5,8,1),
	(51,'Isaac Conley','Stabbed.','Prison inmate, on orders from Jack Welker (contracted by Walter White)','Unknown',5,8,1),
	(52,'William Moniz','Stabbed.','Prison inmate, on orders from Jack Welker (contracted by Walter White)','Unknown',5,8,1),
	(53,'Harris Bolvin','Stabbed.','Prison inmate, on orders from Jack Welker (contracted by Walter White)','Unknown',5,8,1),
	(54,'Raymond Martinez','Stabbed.','Prison inmate, on orders from Jack Welker (contracted by Walter White)','Unknown',5,8,1),
	(55,'Dennis Markowski','Set on fire.','Prison inmate, on orders from Jack Welker (contracted by Walter White)','Help me!',5,8,1),
	(57,'Declan','Shot in the head.','Jack Welker, on orders from Lydia Rodarte-Quayle.','*grunting',5,10,1),
	(58,'Steven Gomez','Shot several times.','Jack Welker and the White Supremacist gang.','You heard the man, put ''em down!',5,14,1),
	(59,'Hank Schrader','Shot in the head.','Jack Welker','Do what you''re gonna go',5,14,1),
	(60,'Andrea Cantillo','Shot in the head','Todd Alquist','Where?',5,15,1),
	(1,'Emilio Koyama','Poisoned by phosphine gas.','Walter White','**Cough',1,1,1),
	(26,'Victor','Throat slit with a boxcutter.','Gustavo Fring','The steps never change, and I know the steps.',4,1,1),
	(14,'Coyote driver','Shot in the head.','Leonel Salamanca','What the hell''s going on in there?',3,1,1),
	(4,'Gonzo','Crushed under car in junkyard.','Accidental Death','Unknown',2,1,1),
	(10,'Combo','Shot in abdomen.','Toman Cantillo','What are you waiting for, go!',2,11,1),
	(62,'Todd Alquist','Garroted (Strangled by wire).','Jesse Pinkman','Mr. White...',5,16,1),
	(63,'Jack Welker','Shot in the head.','Walter White','If you pull that trigger, you''ll never...',5,16,1),
	(64,'Lydia Rodarte-Quayle','Poisoned with ricin.','Walter White','Oh my god.',5,16,1),
	(65,'Walter White','Shot by remote-activated machine gun.','Walter White','Well... goodbye Lydia.',5,16,1),
	(12,'Unnamed passengers on the Wayfarer 515 and JM 21 flights','Flights collided due to poor air traffic control.','Donald Margolis, by extension of Walter White.','Unknown',2,13,167),
	(5,'Tuco Salamanca','Shot to the head.','Hank Schrader (Henry Schrader)','Tell me what you did, Walter!',2,2,1);

