CREATE TABLE IF NOT EXISTS quotes (
    "quote_id" INT PRIMARY KEY,
    "quote" TEXT,
    "author" TEXT,
    "series" TEXT,
    FOREIGN KEY(author) REFERENCES characters(name)
);
INSERT INTO quotes VALUES (1,'I am not in danger, Skyler. I am the danger!','Walter White','Breaking Bad'),
	(2,'Stay out of my territory.','Walter White','Breaking Bad'),
	(3,'IFT','Skyler White','Breaking Bad'),
	(4,'I watched Jane die. I was there. And I watched her die. I watched her overdose and choke to death. I could have saved her. But I didn’t.','Walter White','Breaking Bad'),
	(5,'Say my name.','Walter White','Breaking Bad'),
	(6,'Congratulations, you’ve just left your family a second-hand Subaru.','Saul Goodman','Breaking Bad'),
	(7,'Yeah, you do seem to have a little s*** creek action going... You know, FYI, you can buy a paddle.','Saul Goodman','Breaking Bad'),
	(8,'Tread lightly.','Walter White','Breaking Bad'),
	(9,'Funyuns are awesome.','Jesse Pinkman','Breaking Bad'),
	(10,'Ooooooh, wire.','Jesse Pinkman','Breaking Bad'),
	(11,'A robot?!','Jesse Pinkman','Breaking Bad'),
	(12,'What good is being an outlaw when you have responsibilities.','Jesse Pinkman','Breaking Bad'),
	(13,'You forgot your ice trays! YOU''RE GONNA NEED THE ICE TRAYS!','Jesse Pinkman','Breaking Bad'),
	(14,'Yeah, and thanks, Daddy Warbucks, but that was before my housing situation went completely testicular on me, okay?','Jesse Pinkman','Breaking Bad'),
	(15,'How am I supposed to live here now, huh? My whole house smells like toe cheese and dry cleaning.','Jesse Pinkman','Breaking Bad'),
	(16,'I''m a blow fish! Yeah, Blow fishin'' this up!','Jesse Pinkman','Breaking Bad'),
	(17,'Yeah, totally Kafkaesque','Jesse Pinkman','Breaking Bad'),
	(18,'We make poison for people who don’t care. We probably have the most unpicky customers in the world.','Jesse Pinkman','Breaking Bad'),
	(19,'You don’t need a criminal lawyer. You need a criminal lawyer','Jesse Pinkman','Breaking Bad'),
	(20,'Oh well, heil Hitler, b****!','Jesse Pinkman','Breaking Bad'),
	(21,'Yeah, science!','Jesse Pinkman','Breaking Bad'),
	(22,'Yeah, b****! Magnets!','Jesse Pinkman','Breaking Bad'),
	(23,'Yo 148, 3-to-the-3-to-the-6-to-the-9. Representin’ the ABQ. What up, biatch? Leave it at the tone!','Jesse Pinkman','Breaking Bad'),
	(24,'Jesus Christ, Marie. They''re minerals!','Hank Schrader','Breaking Bad'),
	(25,'My name is Skyler White, yo.','Skyler White','Breaking Bad'),
	(26,'Someone has to protect this family, from the man that protects this family.','Skyler White','Breaking Bad'),
	(27,'Shut up! Shut up! Shut up!','Skyler White','Breaking Bad'),
	(28,'I''m waiting for the cancer to come back.','Skyler White','Breaking Bad'),
	(29,'I can''t remember the last time I was happy.','Skyler White','Breaking Bad'),
	(30,'You''re my free pass.... Bitch!','Jesse Pinkman','Breaking Bad'),
	(63,'Chemistry is the study of matter, but I prefer to see it at the study of change.','Walter White','Breaking Bad'),
	(64,'You asked me if I was in the meth business or the money business. Neither. I am in the empire business','Walter White','Breaking Bad'),
	(65,'Smoking marijuana, eating cheetos, and masturbating do not constitute plans in my book.','Walter White','Breaking Bad'),
	(66,'I did it for me. I liked it. I was good at it. And I was really... I was alive.','Walter White','Breaking Bad'),
	(67,'We''re done when i say we''re done.','Walter White','Breaking Bad'),
	(68,'Did you not plan for this contingency? I mean, the Starship Enterprise had a self-destruct button.','Saul Goodman','Breaking Bad'),
	(69,'There''s no honor among thieves... Except for us of course.','Saul Goodman','Breaking Bad'),
	(70,'Don''t drink and drive. But if you do, call me.','Saul Goodman','Breaking Bad'),
	(71,'Some people are immune to good advice.','Saul Goodman','Breaking Bad'),
	(72,'You either run from things, or you face them, Mr. White.','Jesse Pinkman','Breaking Bad'),
	(73,'You add a plus douce bag to a minus douche bag and you get, like, zero douche bags.','Jesse Pinkman','Breaking Bad'),
	(74,'Yeah, totally Kafkaesque.','Jesse Pinkman','Breaking Bad'),
	(75,'Hey, you girls. Want to meet my fat stack?','Jesse Pinkman','Breaking Bad'),
	(76,'Everyone sounds like Meryl Streep with a gun to their head.','Mike Ehrmantraut','Breaking Bad'),
	(77,'The next time you bring a gun to a job without telling me, I will stick it up your ass sideways.','Mike Ehrmantraut','Breaking Bad'),
	(78,'You know how they say, ''It''s been a pleasure?'' It hasn''t.','Mike Ehrmantraut','Breaking Bad'),
	(79,'Big doings today. The order of the day is ''eyes open, mouth shut.''','Mike Ehrmantraut','Breaking Bad'),
	(80,'You''re an insane, degenerate piece of filth, and you deserve to die.','Walter White','Breaking Bad'),
	(81,'You two suck at peddling meth.','Saul Goodman','Breaking Bad'),
	(82,'Mas his death satisfy you.','Gus Fring','Breaking Bad'),
	(83,'La familia es todo.','Hector Salamanca','Breaking Bad'),
	(84,'I will kill your wife, I will kill your son, I will kill your infant daughter.','Gus Fring','Breaking Bad'),
	(85,'It’s discreet, like a stripper pole in a mosque.','Jimmy McGill','Better Call Saul'),
	(86,'I''m a lawyer, not a criminal','Jimmy McGill','Better Call Saul'),
	(87,'Only two things I know about Albuquerque – Bugs Bunny should’ve taken a left turn there. And give me a hundred tries, I’ll never be able spell it.','Jimmy McGill','Better Call Saul'),
	(88,'I am not good at Building Shit , you know I’m excellent at Tearing it down','Jimmy McGill','Better Call Saul'),
	(89,'I know what stopped me. And you know what? It’s never stopping me again.','Jimmy McGill','Better Call Saul'),
	(90,'Perfection is the Enemy of Perfectly Adequate','Jimmy McGill','Better Call Saul'),
	(91,'Hail Satan. I submit to the dark side.','Jimmy McGill','Better Call Saul'),
	(92,'There’s no honor among thieves… except for us of course','Jimmy McGill','Better Call Saul'),
	(93,'Some people are immune to good advice.','Jimmy McGill','Better Call Saul'),
	(94,'Money is the Point.','Jimmy McGill','Better Call Saul'),
	(95,'You Know the expression it’s been a pleasure... well it hasn’t.','Mike Ehrmantraut','Better Call Saul'),
	(96,'Winning Doesn’t Always Mean Getting a Favorable Verdict at Trial.','Kim Wexler','Better Call Saul'),
	(97,'You know what happened. The question is, can you live with it?','Mike Ehrmantraut','Better Call Saul'),
	(98,'Slippin’ Jimmy with a law degree is like a chimp with a machine gun','Chuck McGill','Better Call Saul'),
	(99,'No one ever accused you of being lazy.. every other sin in the book , but not that one.','Chuck McGill','Better Call Saul'),
	(100,'FYI, old people adore me.','Jimmy McGill','Better Call Saul'),
	(101,'I''m gonna be a damn good lawyer, and people are gonna know about it','Jimmy McGill','Better Call Saul'),
	(102,'S''all good, man.','Jimmy McGill','Better Call Saul');
